@startuml

'http://plantuml.com/skinparam.html'
skinparam handwritten true
skinparam monochrome false
skinparam defaultFontName FG Virgil
skinparam shadowing false

title P2P-FileShare

package "presentation" {

    class DirectoryTableView
    class DownloadingDialog
    class EditConfigurationDialog
    class RemoteFilenamesTableView
    class P2PFileShareApp {

        + {static} main : void
    }
}

package "application" {
    class ManageSharedFilesController
    class CommunicationsController
    class EditConfigurationsController
}

package "networking" {

    class UdpCommunication
    class TcpCommunication
    class RemoteFilenameListProtocol
}

package "domain" {

    class RemoteFilename {
        filename : String
        username : String
        address : InetAddress
        tcpPort : Integer
        active : Boolean

        +activate()
        +refresh()
        -deactivate()
        +notifyObservers()
    }
    class RemoteFilenameList {
        list : ObservableList
        +update()
    }
    class Directory {
        directory : Path
        filter : FileFilter
        watcher : WatchService
        +getFiles() : File[]
    }
}

package "util" {
    class Constants
    class ByteUtil
    class OSUtil
    class StringUtil
}

application .> domain
application ...> networking
networking ...> domain
presentation ...> application

networking ..> util
domain ..> util
presentation ..> util
application ..> util

@enduml

P2PFileShareApp ..> DirectoryTableView
P2PFileShareApp ..> DownloadingDialog
P2PFileShareApp ..> EditConfigurationDialog
P2PFileShareApp ..> RemoteFilenamesTableView


/'
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10

class UdpCommunication {
  username
  password
  +sign_in()
}
'/