@startuml

'http://plantuml.com/skinparam.html'
skinparam handwritten true
skinparam monochrome false
skinparam defaultFontName FG Virgil
skinparam shadowing false

Cliente -> Server: download Request
Server --> Cliente: accept Request
Server -> Server: next request
note right: creates a new thread\nfor the connection
Cliente -> ConnectionThread: \nsend file name length
Cliente -> ConnectionThread: send file name
ConnectionThread -> ConnectionThread: find file
Cliente <- ConnectionThread: \nsend file size
Cliente <- ConnectionThread: send file
ConnectionThread -> ConnectionThread: close socket
Cliente -> Cliente: close socket
@enduml